"use client";
import { useState, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { VideoPlayer } from "./components/VideoPlayer";

const mdComponents = {
  img: ({ node, ...props }) => {
    const isVideo = props.src && props.src.toLowerCase().endsWith('.mp4');
    const isProduct = props.alt && props.alt.toLowerCase().includes('product');

    if (isVideo) {
      return (
        <span style={{ display: 'block', marginTop: 12, marginBottom: 12, borderRadius: 12, overflow: 'hidden', boxShadow: '0 4px 12px rgba(0,0,0,0.15)' }}>
          <VideoPlayer {...props} style={{ width: '100%', height: 'auto', display: 'block', objectFit: 'cover', maxHeight: 220 }} />
        </span>
      );
    }

    if (isProduct) {
      return (
        <span style={{ display: 'block', marginTop: 12, marginBottom: 12, borderRadius: 12, overflow: 'hidden', boxShadow: '0 4px 12px rgba(0,0,0,0.15)', maxWidth: '240px' }}>
          <img loading="lazy" {...props} style={{ width: '100%', aspectRatio: '1/1', display: 'block', objectFit: 'cover' }} />
        </span>
      );
    }

    return (
      <span style={{ display: 'block', marginTop: 12, marginBottom: 12, borderRadius: 12, overflow: 'hidden', boxShadow: '0 4px 12px rgba(0,0,0,0.15)' }}>
        <img loading="lazy" {...props} style={{ width: '100%', height: 'auto', display: 'block', objectFit: 'cover', maxHeight: 220 }} />
      </span>
    );
  },
  a: ({ node, ...props }) => {
    if (props.href && props.href.startsWith('#store_')) {
      const storeId = props.href.replace('#store_', '');
      return (
        <a {...props} onClick={(e) => {
          e.preventDefault();
          window.dispatchEvent(new CustomEvent('sera:openStore', { detail: storeId }));
        }} style={{ display: 'inline-block', padding: '6px 14px', background: 'linear-gradient(135deg, #c8b89a 0%, #a8987a 100%)', color: '#000', borderRadius: 6, textDecoration: 'none', fontWeight: 700, marginTop: 0, marginBottom: 12, fontSize: 11, cursor: 'pointer', border: '1px solid #e0d0b0', letterSpacing: '0.5px', textTransform: 'uppercase' }}>
          View Store
        </a>
      );
    }
    if (props.href && props.href.startsWith('#product_')) {
      const productId = props.href.replace('#product_', '');
      return (
        <a {...props} onClick={(e) => {
          e.preventDefault();
          window.dispatchEvent(new CustomEvent('sera:openProduct', { detail: productId }));
        }} style={{ display: 'inline-block', padding: '6px 14px', background: 'transparent', color: '#c8b89a', borderRadius: 6, textDecoration: 'none', fontWeight: 700, marginTop: 0, marginBottom: 12, fontSize: 11, cursor: 'pointer', border: '1px solid #c8b89a', letterSpacing: '0.5px', textTransform: 'uppercase' }}>
          View Product
        </a>
      );
    }
    return <a {...props} style={{ color: '#c8b89a', textDecoration: 'underline' }} />;
  },
  hr: () => null, // Visually remove any horizontal lines generated by markdown
  table: ({ node, ...props }) => (
    <div style={{ overflowX: 'auto', marginTop: 12, marginBottom: 12 }}>
      <table {...props} style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12.5, fontFamily: "'DM Sans', sans-serif" }} />
    </div>
  ),
  thead: ({ node, ...props }) => (
    <thead {...props} style={{ background: 'rgba(200,184,154,0.08)' }} />
  ),
  th: ({ node, ...props }) => (
    <th {...props} style={{ padding: '8px 12px', textAlign: 'left', color: '#c8b89a', fontWeight: 700, fontSize: 11, letterSpacing: '0.5px', textTransform: 'uppercase', borderBottom: '1px solid rgba(200,184,154,0.2)' }} />
  ),
  td: ({ node, ...props }) => (
    <td {...props} style={{ padding: '8px 12px', color: '#d0d0da', borderBottom: '1px solid rgba(255,255,255,0.04)', verticalAlign: 'top' }} />
  ),
  tr: ({ node, ...props }) => (
    <tr {...props} style={{ transition: 'background 0.15s' }} onMouseEnter={e => e.currentTarget.style.background='rgba(200,184,154,0.04)'} onMouseLeave={e => e.currentTarget.style.background='transparent'} />
  ),
};

const C = {
  bg: "#090909", s0: "#0d0d0f", s1: "#111114", s2: "#161618",
  b0: "#141416", b1: "#1c1c1f", b2: "#252528",
  t0: "#f0f0f4", t1: "#9090a0", t2: "#505060", t3: "#2a2a34",
  mono: "'IBM Plex Mono', 'JetBrains Mono', monospace",
  sans: "'Geist', 'Inter', sans-serif",
};

const fmtTime = (ts) => {
  if (!ts) return "";
  const d = new Date(ts * 1000);
  return [d.getHours(), d.getMinutes(), d.getSeconds()]
    .map(n => String(n).padStart(2, "0")).join(":");
};

const groupIntoPhases = (rows) => {
  if (!rows || rows.length === 0) return [];
  const phases = [];
  let currentPhase = null;

  rows.forEach(r => {
    // If it has a title, we group by title. Otherwise group by phase name.
    const groupKey = r.title ? `title_${r.title}` : `phase_${r.phase || "planning"}`;
    const displayName = r.title || r.phase || "planning";

    if (!currentPhase || currentPhase.groupKey !== groupKey) {
      if (currentPhase) phases.push(currentPhase);
      currentPhase = { id: `ph_${phases.length}`, groupKey, name: displayName, logs: [], done: r.done, active: false };
    }
    currentPhase.logs.push(r);
    if (!r.done) currentPhase.done = false;
  });
  if (currentPhase) phases.push(currentPhase);

  const activeIndex = phases.findIndex(p => !p.done);
  if (activeIndex !== -1) phases[activeIndex].active = true;

  phases.forEach((p, i) => {
    if (activeIndex !== -1 && i < activeIndex) p.done = true;
    if (activeIndex === -1) p.done = true;
  });
  return phases;
};

const Cursor = () => (
  <span style={{
    display: "inline-block", width: 6, height: "0.8em",
    background: C.t2, marginLeft: 2, verticalAlign: "text-bottom",
    animation: "blink 1s step-end infinite",
  }} />
);

// Map phase names to meaningful status messages for the user
const phaseToStatusMsg = (phase, tool) => {
  if (tool) {
    if (tool.includes('batch_create') || tool.includes('publish')) return "Building your storefront";
    if (tool.includes('generate_store_assets') || tool.includes('image')) return "Generating visuals & assets";
    if (tool.includes('get_stores') || tool.includes('find')) return "Fetching store data";
    return `Running ${tool.replace(/_/g, ' ')}`;
  }
  const p = (phase || '').toLowerCase();
  if (p.includes('analy')) return "Analyzing your request";
  if (p.includes('brand') || p.includes('design')) return "Crafting brand identity";
  if (p.includes('catalog') || p.includes('product')) return "Building product catalog";
  if (p.includes('asset') || p.includes('gen') || p.includes('image')) return "Generating visuals";
  if (p.includes('layout') || p.includes('schema')) return "Structuring storefront layout";
  if (p.includes('polic')) return "Defining store policies";
  if (p.includes('execut') || p.includes('tool')) return "Executing operations";
  if (p.includes('verif') || p.includes('valid')) return "Verifying results";
  return "Working on your request";
};

// â”€â”€â”€ ActiveRuntime (Expanded Streaming State) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
function ActiveRuntime({ activeEvents }) {
  const phases = groupIntoPhases(activeEvents);
  if (phases.length === 0) return null;

  const activePhase = phases.find(ph => ph.active || !ph.done) || phases[phases.length - 1];
  if (!activePhase) return null;

  const isTitleBased = activePhase.groupKey.startsWith("title_");
  const lastLog = activePhase.logs[activePhase.logs.length - 1];
  const title = isTitleBased ? activePhase.name : activePhase.name.replace(/_/g, ' ');
  const message = isTitleBased ? (lastLog?.message || "") : phaseToStatusMsg(activePhase.name, lastLog?.tool);
  const agentName = lastLog?.agent || "";
  const isActive = true;

  return (
    <div style={{ marginTop: 8, marginBottom: 12, fontFamily: C.sans, width: "100%" }}>
      <div style={{ fontSize: 13.5, fontWeight: 500, color: "#e0d0b0", display: 'flex', alignItems: 'center' }}>
        {title.replace(/\.+$/, '')}
        {isActive && (
          <span className="dots" style={{ display: 'inline-flex', marginLeft: 6 }}>
            <span></span><span></span><span></span>
          </span>
        )}
      </div>
      {message && (
        <div className="sera-chat markdown-body" style={{
          fontSize: 12,
          color: "#9090a0",
          marginTop: 4,
          lineHeight: 1.5,
          width: "100%",
          display: "-webkit-box",
          WebkitLineClamp: 6,
          WebkitBoxOrient: "vertical",
          overflow: "hidden",
          textOverflow: "ellipsis"
        }}>
          <ReactMarkdown remarkPlugins={[remarkGfm]} components={mdComponents}>{message}</ReactMarkdown>
        </div>
      )}
      <style>{`
        .dots span {
          width: 3.5px;
          height: 3.5px;
          margin: 0 1.5px;
          background-color: currentColor;
          border-radius: 50%;
          display: inline-block;
          animation: dots-blink 1.4s infinite both;
          opacity: 0.35;
        }
        .dots span:nth-child(2) {
          animation-delay: .2s;
        }
        .dots span:nth-child(3) {
          animation-delay: .4s;
        }
        @keyframes dots-blink {
          0% { opacity: .35; }
          20% { opacity: 1; }
          100% { opacity: .35; }
        }
      `}</style>
    </div>
  );
}

// â”€â”€â”€ CompletedReport (Expanded Log Grid) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
function CompletedReport({ activeEvents }) {
  const phases = groupIntoPhases(activeEvents);
  if (phases.length === 0) return null;

  const getProfessionalResult = (phaseName, rawLogs) => {
    const p = phaseName.toLowerCase();
    if (p.includes("analy")) return "Market & requirements identified";
    if (p.includes("brand") || p.includes("design")) return "Brand identity established";
    if (p.includes("catalog") || p.includes("product")) return "Product catalog generated";
    if (p.includes("layout") || p.includes("asset")) return "Storefront layout structured";
    if (p.includes("polic")) return "Store policies generated";
    if (p.includes("execut") || p.includes("tool")) return "Operations executed successfully";
    return "Task completed";
  };

  return (
    <div style={{ marginTop: 8, display: 'flex', flexDirection: 'column', gap: 12, fontFamily: C.sans }}>
      {phases.map(ph => {
        const isTitleBased = ph.groupKey.startsWith("title_");
        const lastLog = ph.logs[ph.logs.length - 1];
        const title = isTitleBased ? ph.name : ph.name.replace(/_/g, ' ');
        const message = isTitleBased ? (lastLog?.message || "Completed task") : getProfessionalResult(ph.name, ph.logs);

        return (
          <div key={ph.id}>
            <div style={{ fontSize: 13, fontWeight: 500, color: "#e0d0b0" }}>
              {title}
            </div>
            <div className="sera-chat markdown-body" style={{ fontSize: 12, color: "#9090a0", marginTop: 2, lineHeight: 1.5, width: "100%" }}>
              <ReactMarkdown remarkPlugins={[remarkGfm]} components={mdComponents}>{message}</ReactMarkdown>
            </div>
          </div>
        );
      })}
    </div>
  );
}

// â”€â”€â”€ RuntimeLog â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
function RuntimeLog({ events, milestones, isStreaming }) {
  const useRich = events && events.length > 0;
  const rows = useRich ? events : milestones.map(m => ({ message: m.text, done: m.status === "done", phase: "execution" }));

  if (rows.length === 0) return null;

  if (isStreaming) {
    return <ActiveRuntime activeEvents={rows} />;
  }
  return <CompletedReport activeEvents={rows} />;
}

// â”€â”€â”€ FinalOut (Replaces old ResponseText and Summary) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
function FinalOut({ text, summary, planData, isStreaming, finalDurStr }) {
  if (isStreaming) {
    return text ? (
      <div style={{ fontFamily: C.sans, fontSize: 13, color: "inherit", opacity: 0.8, lineHeight: 1.5, margin: "6px 0 10px 0" }}>
        {text} <Cursor />
      </div>
    ) : null;
  }

  const title = planData?.title;
  const sub = planData?.subtitle || summary;
  const hasPlan = !!planData?.products?.length;

  return (
    <div className="final-out">
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div className="final-label">{hasPlan ? "store ready" : text}</div>
      </div>
      {title && <div className="final-title">{title}</div>}
      {sub && <div className="final-sub">{sub}</div>}
      {hasPlan && (
        <div className="final-tags">
          <span className="ftag ok">âœ“ launched</span>
          <span className="ftag">commerce</span>
          <span className="ftag">{planData.products.length} products</span>
        </div>
      )}
    </div>
  );
}

// â”€â”€â”€ Actions â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
function Actions({ actions, onAction }) {
  if (!actions?.length) return null;
  return (
    <div className="actions" style={{ display: "flex" }}>
      {actions.map(a => {
        const cls = a.variant === "approve" ? "act ok" : a.variant === "reject" ? "act no" : "act";
        const icon = a.variant === "approve" ? "âœ“ " : a.variant === "reject" ? "&times; " : "â†© ";
        return (
          <button
            key={a.key}
            onClick={() => onAction?.(a.key, a.variant)}
            className={cls}
          >
            {icon}{a.label.replace("Approve", "Approve").replace("Reject", "Reject")}
          </button>
        );
      })}
    </div>
  );
}

// â”€â”€â”€ Thinking â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const Thinking = ({ startTs, text = "thinking", subtext = "Analyzing query..." }) => {
  const [internalStartTs] = useState(Date.now());
  const effectiveStartTs = startTs || internalStartTs;
  const [nowMs, setNowMs] = useState(Date.now());

  useEffect(() => {
    const timer = setInterval(() => setNowMs(Date.now()), 100);
    return () => clearInterval(timer);
  }, []);

  const sec = Math.max(1, Math.round((nowMs - effectiveStartTs) / 1000));

  return (
    <div style={{ cursor: "default", opacity: 1, color: "#c8b89a", fontFamily: C.sans, marginBottom: 12 }}>
      <div className="phase-name running" style={{ fontSize: 13.5, fontWeight: 500, display: 'flex', alignItems: 'center' }}>
        {(text || "").replace(/\.+$/, '')}
        <span className="dots" style={{ display: 'inline-flex', marginLeft: 6 }}>
          <span></span><span></span><span></span>
        </span>
        {effectiveStartTs && sec > 0 && <span className="phase-dur" style={{ marginLeft: 6, fontSize: 11, color: "#60606d" }}>{sec}s</span>}
      </div>
      {subtext && (
        <div style={{
          fontSize: 12,
          color: "#9090a0",
          marginTop: 4,
          lineHeight: 1.5,
          display: "-webkit-box",
          WebkitLineClamp: 6,
          WebkitBoxOrient: "vertical",
          overflow: "hidden",
          textOverflow: "ellipsis"
        }}>
          {subtext}
        </div>
      )}
    </div>
  );
};

// â”€â”€â”€ MAIN EXPORT â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export function SeraAgentMessage({ message, onAction }) {
  const [logsOpen, setLogsOpen] = useState(false);
  const {
    state = "complete",
    isStreaming = false,
    milestones = [],
    events = [],
    runtime = null,
    cognition = [],
    summary = null,
    tools = [],
    content = "",
    actions = [],
    planData = null,
    chat = null,
    ephemeralThought = null,
    executionLifecycle = "completed",
  } = message;

  const activeEvents = runtime || events || cognition || [];
  const hasActualWork = activeEvents.some(e => e.type === 'execution' || e.type === 'cognition' || e.type === 'thinking');
  const hasRuntime = hasActualWork;

  let currentText = "thinking";
  if (isStreaming) {
    if (executionLifecycle === "planning") currentText = "planning team";
    else if (executionLifecycle === "executing") currentText = "executing strategy";
    else if (executionLifecycle === "consensus") currentText = "reaching consensus";
    else if (executionLifecycle === "ui_ready" || executionLifecycle === "narrating") currentText = "writing narrative";
    else if (activeEvents.length > 0) {
      const active = activeEvents.find(e => !e.done) || activeEvents[activeEvents.length - 1];
      if (active && active.phase) {
        const phaseStr = active.phase.replace(/_/g, ' ').toLowerCase();
        if (phaseStr.includes('analy')) currentText = "analyzing";
        else if (phaseStr.includes('gen') || phaseStr.includes('asset')) currentText = "generating assets";
        else if (phaseStr.includes('fetch') || phaseStr.includes('query')) currentText = "fetching data";
        else if (phaseStr.includes('design')) currentText = "designing layout";
        else currentText = phaseStr;
      }
    }
  }

  const startTs = activeEvents.length > 0 ? (activeEvents[0].localTs || (activeEvents[0].timestamp ? activeEvents[0].timestamp * 1000 : null)) : null;
  const endTs = activeEvents.length > 0 ? (activeEvents[activeEvents.length - 1].localTs || (activeEvents[activeEvents.length - 1].timestamp ? activeEvents[activeEvents.length - 1].timestamp * 1000 : null)) : null;
  let finalDurStr = "";
  if (!isStreaming && startTs && endTs) {
    const sec = Math.max(1, Math.round((endTs - startTs) / 1000));
    finalDurStr = sec + "s";
  }

  const INTRO_RE = /^(I\s+am\s+(a\s+large|an?\s+AI|SERA)|As\s+(an?\s+)?(AI)|Certainly[,!]|Sure[,!]\s+I|Absolutely[,!])/i;
  let displayText = content
    ? content
      .split("\n")
      .filter(line => !INTRO_RE.test(line.trim()))
      .join("\n")
      .trim()
    : "";

  // When streaming, don't show displayText if it's internal JSON data
  if (isStreaming && (displayText.trim().startsWith("{") || displayText.trim().startsWith("```json"))) {
    displayText = "";
  }

  const logsComponent = hasRuntime && (
    <RuntimeLog
      events={activeEvents}
      milestones={milestones}
      isStreaming={isStreaming}
    />
  );
  const isSimpleChat = !hasRuntime && !planData;
  const headerLabel = planData ? displayText : (hasRuntime ? "Search completed" : "");

  const finalOutComponent = isSimpleChat ? (
    isStreaming ? (
      <div className="sera-chat markdown-body" style={{ fontFamily: C.sans, fontSize: 13, lineHeight: 1.5, marginTop: 8, opacity: 0.7 }}>
        <ReactMarkdown remarkPlugins={[remarkGfm]} components={mdComponents}>{chat || displayText}</ReactMarkdown> <Cursor />
      </div>
    ) : (
      <div className="sera-chat markdown-body" style={{ fontFamily: C.sans, fontSize: 13, lineHeight: 1.65, marginTop: 4 }}>
        <ReactMarkdown remarkPlugins={[remarkGfm]} components={mdComponents}>{chat || displayText}</ReactMarkdown>
      </div>
    )
  ) : (
    <FinalOut text={headerLabel} summary={summary} planData={planData} isStreaming={isStreaming} finalDurStr={finalDurStr} />
  );
  // Custom header for completed complex tasks
  const completedHeader = !isStreaming && hasRuntime && (
    <div className="sera-card" style={{ borderRadius: 8, overflow: 'hidden', marginBottom: 8, background: '#111114', border: '1px solid #1c1c1f' }}>
      <div
        onClick={() => setLogsOpen(!logsOpen)}
        style={{ padding: "10px 14px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", transition: "background 0.2s" }}
      >
        <div style={{ flex: 1, fontSize: 13, color: '#f0f0f4', fontFamily: C.sans }}>
          Completed â€” {groupIntoPhases(activeEvents).length} steps {finalDurStr && `(${finalDurStr})`}
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 6, color: '#9090a0' }}>
          <span className="chevron-sm" style={{ padding: 4, transform: logsOpen ? 'rotate(-90deg)' : 'rotate(0deg)', transition: 'transform 0.2s' }}>âŒ„</span>
        </div>
      </div>
      {logsOpen && (
        <div style={{ padding: "0 14px 14px 14px" }}>
          {logsComponent}
        </div>
      )}
    </div>
  );

  return (
    <div style={{ padding: "2px 0" }}>
      {isStreaming ? (
        <>
          {displayText && (
            <div className="sera-chat markdown-body" style={{ fontFamily: C.sans, fontSize: 13, lineHeight: 1.5, marginTop: 4, marginBottom: 8, opacity: 0.9 }}>
              <ReactMarkdown remarkPlugins={[remarkGfm]} components={mdComponents}>{displayText}</ReactMarkdown>
            </div>
          )}
          {!displayText && !hasRuntime && <Thinking startTs={startTs} text={currentText} subtext={ephemeralThought || ""} />}
          {logsComponent}
        </>
      ) : isSimpleChat ? (
        finalOutComponent
      ) : (
        <>
          {completedHeader}

          {planData && (
            <FinalOut text={headerLabel} summary={summary} planData={planData} isStreaming={isStreaming} finalDurStr={finalDurStr} />
          )}

          {!planData && (chat || displayText) && (
            <div className="sera-chat markdown-body" style={{ fontFamily: C.sans, fontSize: 13, lineHeight: 1.65, marginTop: 4 }}>
              <ReactMarkdown remarkPlugins={[remarkGfm]} components={mdComponents}>{chat || displayText}</ReactMarkdown>
            </div>
          )}
        </>
      )}

      {!isSimpleChat && planData && chat && (
        <div style={{
          marginTop: 14,
          paddingTop: 14,
          borderTop: '1px solid #1c1c1f',
        }}>
          <div className="sera-chat markdown-body" style={{
            fontFamily: C.sans,
            fontSize: 13.5,
            lineHeight: 1.65,
            color: '#d8d8e0'
          }}>
            <ReactMarkdown remarkPlugins={[remarkGfm]} components={mdComponents}>{chat}</ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  );
}

export default SeraAgentMessage;

